ChasingSomeone/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ChasingSomeone/', include('ChasingSomeoneApp.urls', namespace="ChasingSomeoneApp")),
]

ChasingSomeoneApp/urls.py
from django.conf.urls import url
from .views import UserView, AuthView, FollowerView, AccountView, StatusView

urlpatterns = [
    url(r'^$', AuthView.user_login, name="user_login"),
    url(r'^login/$', AuthView.user_login, name="user_login"),
    url(r'^register/$', UserView.register, name='register'),
    url(r'^user_activate/(?P<user_pk>[0-9]+)/$', UserView.user_activate, name="user_activate"),
    url(r'^home/$', UserView.user_home, name='user_home'),
    url(r'^logout/$', AuthView.user_logout, name='user_logout'),

    url(r'browse_following/$', FollowerView.browse_following, name="browse_following"),
    url(r'^add_follower/$', FollowerView.add_follower, name="add_follower"),
    url(r'^delete_follower/$', FollowerView.delete_follower, name="delete_follower"),

    url(r'^verify_account/$', AccountView.http_verify_account, name="verify_account"),
    url(r'^save_account/$', AccountView.http_save_account, name="save_account"),
    url(r'^delete_account/$', AccountView.http_delete_account, name="delete_account"),

    url(r'refresh_status_site/$', StatusView.refresh_status_by_site, name="refresh_status_site"),
    url(r'refresh_status_flr/$', StatusView.refresh_status_by_flr, name='refresh_status_flr'),
]

ChasingSomeoneApp/forms.py
from django import forms
from ChasingSomeoneApp.models.UserProfile import UserProfile, User
from django.contrib.auth.forms import UserCreationForm

# class UserForm(forms.ModelForm):
class SignUpForm (UserCreationForm):

    email = forms.EmailField(label='Email Address', max_length=75)

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            user = User.objects.get(email=email)
            raise forms.ValidationError("This email address exists. Did you forget your password?")
        except User.DoesNotExist:
            return email

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.email = self.cleaned_data["email"]
        user.is_active = False
        if commit:
            user.save()
        return user

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ()

ChasingSomeoneApp/views/AccountView.py
__author__ = 'charleszhuochen'

'''AccountView is an inside View for controlling social accounts detials. it is like a controller of accounts'''
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, JsonResponse

from ChasingSomeoneApp.views import  TWAccountView, QrAccountView

from ChasingSomeoneApp.models.Follower import Follower

act_type_list = ['twitter', ]

# act_type, act_details
@login_required
def http_verify_account(request):
    if request.is_ajax():
        json_data = json.loads(request.body)
        if 'act_type' not in json_data:
            return HttpResponse(False)
        verify_result = verify_account(**json_data)
        if verify_result == False or verify_result == '404':
            return HttpResponse(verify_result)
        return JsonResponse(verify_result)
    raise Http404


@login_required
def http_save_account(request):
    if request.is_ajax():
        json_data = json.loads(request.body)
        if 'act_type' not in json_data:
            return HttpResponse(False)
        try:
            flr_name = json_data.get('flr_name')
        except KeyError:
            print("keyError in AccountView:http_save_account\n")
            return HttpResponse(False)
        try:
            follower = Follower.objects.get(name=flr_name)
        except Follower.DoesNotExist:
            print("cannot find follower with flr_name %s\n" % flr_name)
            return HttpResponse(False)

        save_result = save_account(follower, **json_data)
        return HttpResponse(save_result)
    raise Http404


@login_required
def http_delete_account(request):
    if request.is_ajax():
        json_data = json.loads(request.body)
        if 'act_type' not in json_data or 'flr_name' not in json_data:
            return HttpResponse(False)
        delete_result = delete_account(json_data.get('flr_name'), json_data.get('act_type'))
        return HttpResponse(delete_result)
    raise Http404


# follower:Follower, act_tpye, act_details
# tw_account needs details from crawler
def save_account(follower, **kwargs):
    if 'act_type' not in kwargs:
        return False
    verify_result = verify_account(**kwargs)
    if verify_result == '404' or verify_result is False:
        return verify_result
    kwargs.update(verify_result)
    try:
        act_type = kwargs['act_type']
    except KeyError:
        return False
    if act_type == u'twitter':
        act_kwargs = dict()
        try:
            act_kwargs['act_id'] = kwargs.get('act_id')
            act_kwargs['screen_name'] = kwargs.get('screen_name')
        except KeyError:
            print("key error in AccountView:save_account() with act_type 'twitter'\n")
            return False

        return TWAccountView.save_account(follower, **act_kwargs)
    elif act_type == u'quora':
        act_kwargs = dict()
        try:
            act_kwargs['user_name'] = kwargs['user_name']
        except KeyError:
            return False
        return QrAccountView.save_account(follower, **act_kwargs)
    return False


def verify_account(**kwargs):
    verify_result = False
    if kwargs.get(u'act_type', None) == u'twitter':
        try:
            verify_kwargs = {'flr_name': kwargs.get('flr_name', None),
                             'act_id': kwargs.get('act_id', None),
                             'screen_name': kwargs.get('screen_name', None)}
        except KeyError:
            print("key error when assign verify_kwargs in twitter\n")
            return False
        verify_result = TWAccountView.verify_account(**verify_kwargs)

    elif kwargs.get(u'act_type', None) == u'quora':

        verify_kwargs = {'flr_name': kwargs.get('flr_name', None),
                         'user_name': kwargs.get('user_name', None)}
        verify_result = QrAccountView.verify_account(**verify_kwargs)
    else:
        pass
    return verify_result


def delete_account(flr_name, act_type):
    if not Follower.objects.filter(name=flr_name).exists():
        return False
    if act_type == u'twitter':
        delete_result = TWAccountView.delete_account(flr_name)
        return delete_result
    elif act_type == u'quora':
        delete_result = QrAccountView.delete_account(flr_name)
        return delete_result
    else:
        # new act type add here
        pass
    return False


def get_flr_accounts(flr_name):
    act_list = []
    for act_type in act_type_list:
        act = get_account(flr_name, act_type)
        if act:
            act_list.append(act)
    return act_list


def get_account(flr_name, act_type):
    if act_type == u'twitter':
        act = TWAccountView.get_account(flr_name)
        if act:
            act['act_type'] = u'twitter'
        return act
    elif act_type == u'quora':
        act = QrAccountView.get_account(flr_name)
        if act:
            act['act_type'] = u'quora'
        return act
    else:
        pass
    return False

ChasingSomeoneApp/views/AuthView.py
__author__ = 'charleszhuochen'
from django.shortcuts import render

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('ChasingSomeoneApp:user_home'))
            else:
                return render(request, 'ChasingSomeoneApp/user_active.html', {'activated': False})
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            error_message = "Wrong email or password."
            context_dict = {'error': True, 'errorMessage': error_message}
            return render(request, 'ChasingSomeoneApp/login.html', context_dict)

    else:
        return render(request, 'ChasingSomeoneApp/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('ChasingSomeoneApp:user_login'))

ChasingSomeoneApp/views/FollowerView.py
__author__ = 'charleszhuochen'

import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse

from ChasingSomeoneApp.models.Follower import Follower
from ChasingSomeoneApp.views import AccountView


def browse_following(request):
    user = request.user
    try:
        follower_list = Follower.objects.filter(user=user)
    except Follower.DoesNotExist:
        follower_list = None
    flr_list = []
    for flr in follower_list:
        flr_detials = {"flr_name": flr.name,
                       "flr_id": flr.id,
                       "url_img": "../../static/img/profile_picture.png"}
        flr_list.append(flr_detials)
    return render(request, 'ChasingSomeoneApp/following.html', {'flr_list': flr_list})

@login_required
def add_follower(request):
    if request.is_ajax():
        if request.method != 'POST':
            raise Http404
        json_data = json.loads(request.body)
        try:
            flr_name = json_data.get(u'flr_name')
        except KeyError:
            print("KeyError in FollowerView:add_follower() when getting flr_name\n")
            return HttpResponse(False)
        if Follower.objects.filter(name=flr_name).exists():
            return HttpResponse(False)
        new_follower = Follower(name=flr_name, user=request.user)
        new_follower.save()
        response_dict = {'flr_id': new_follower.id,
                         'flr_name': new_follower.name}
        return JsonResponse(response_dict)
    else:
        raise Http404


@login_required
def delete_follower(request):
    if request.is_ajax():
        if request.method != 'POST':
            raise Http404
        json_data = json.loads(request.body)
        try:
            flr_name = json_data.get(u'flr_name')
        except KeyError:
            print("KeyError in FollowerView:delete_follower() when getting flr_name\n")
            return HttpResponse(False)
        # act_list = AccountView.get_flr_accounts(flr_name)
        # for act in act_list:
        #     if not AccountView.delete_account(flr_name, act.get('act_type', None)):
        #         print("Error: delete_account return False when delete flr_name '%s', act_type '%s'"
        #               % (flr_name, act.get('act_type', None)))
        try:
            follower = Follower.objects.get(name=flr_name)
        except Follower.DoesNotExist:
            print("Error: FollowerView:delete_follower(): follower %s does not exist" % flr_name)
            return HttpResponse(False)
        follower.delete()
        return HttpResponse(True)
    raise Http404

ChasingSomeoneApp/views/QrAccountView.py
__author__ = 'charleszhuochen'

from ChasingSomeoneApp.crawler.crawler_quora import Crawler_quora
from ChasingSomeoneApp.models.QrAccount import QrAccount


def verify_account(**verify_kwargs):
    if verify_kwargs['flr_name'] is not None:
        if QrAccount.objects.filter(follower__name=verify_kwargs['flr_name']).exists():
            return False
    tw_crawler = Crawler_quora()
    crawler_kwargs = {'user_name': verify_kwargs.get('user_name', None)}
    user_name = tw_crawler.add_follower(**crawler_kwargs)
    if not user_name:
        return '404'
    return {'user_name': user_name}


def save_account(follower, **kwargs):
    new_account = QrAccount(follower=follower)
    new_account.user_name = kwargs['user_name']
    new_account.save()
    return True


def delete_account(follower_name):
    account = QrAccount.objects.get(follower__name=follower_name)
    if account:
        account.delete()
        return True
    else:
        return False


def get_account(flr_name):
    try:
        account = QrAccount.objects.get(follower__name=flr_name)
        return {'user_name': account.user_name}
    except QrAccount.DoesNotExist:
        return False

ChasingSomeoneApp/views/QrStatusView.py
__author__ = 'charleszhuochen'

from ChasingSomeoneApp.models.QrStatus import QrStatus
from ChasingSomeoneApp.crawler.crawler_quora import Crawler_quora


def refresh_status(qr_act_list):
    qr_crawler = Crawler_quora()
    status_list = []
    for act in qr_act_list:
        temp_list = qr_crawler.get_status(user_name=act.user_name)
        if temp_list:
            save_status(act, temp_list)
            status_list.extend(temp_list)
    if len(status_list) > 10:
        status_list = status_list[:10]
    for status in status_list:
        status['act_type'] = 'quora'
    return status_list

def more_status(qr_act_list):
    pass

#current just use target as unique index
def save_status(act, status_list):
    for status in status_list:
        if not QrStatus.objects.filter(target=status.get('target', None)):
            new_status = QrStatus()
            new_status.qrAccount = act
            try:
                new_status.target = status['target']
                new_status.url_profile_img = status['user_profile_image']
                new_status.url_target = status['url']
                new_status.action_type = status['action_type']
                new_status.time_stamp = status['time_stamp']
                new_status.user_profile_name = status['user_name']
            except KeyError:
                continue
            new_status.save()

ChasingSomeoneApp/views/StatusView.py
__author__ = 'charleszhuochen'

import json
import time
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, JsonResponse


from ChasingSomeoneApp.views import TwStatusView
from ChasingSomeoneApp.views import QrStatusView
from ChasingSomeoneApp.models.Follower import Follower
from ChasingSomeoneApp.models.TwAccount import TwAccount
from ChasingSomeoneApp.models.QrAccount import QrAccount

# { 'site_type' : site_type }
@login_required
def refresh_status_by_site(request):
    if request.is_ajax():
        json_data = json.loads(request.body)
        try:
            site_type = json_data['site_type']
        except KeyError:
            return HttpResponse(False)
        user = request.user
        flr_list = Follower.objects.filter(user=user)
        if site_type == 'twitter':
            act_list = []
            since_id = json_data.get('since_id', None)
            for flr in flr_list:
                try:
                    act_list.append(TwAccount.objects.get(follower=flr))
                except TwAccount.DoesNotExist:
                    pass
            status_list = TwStatusView.refresh_status(act_list, since_id)
            return JsonResponse({'status_list': status_list})
        elif site_type == 'quora':
            act_list = []
            for flr in flr_list:
                try:
                    act_list.append(QrAccount.objects.get(follower=flr))
                except QrAccount.DoesNotExist:
                    pass
            status_list = QrStatusView.refresh_status(act_list)
            return JsonResponse({'status_list': status_list})
    raise Http404


# { 'flr_name': flr_name }
@login_required
def refresh_status_by_flr(request):
    if request.is_ajax():
        json_data = json.loads(request.body)
        try:
            flr_name = json_data['flr_name']
        except KeyError:
            return HttpResponse(False)
        lt_st_time = json_data.get('lt_st_time', None)
        status_list = []
        try:
            tw_account = TwAccount.objects.get(follower__name=flr_name)
            status_list.extend(TwStatusView.refresh_status([tw_account, ]))
        except TwAccount.DoesNotExist:
            pass
        try:
            qr_account = QrAccount.objects.get(follower__name=flr_name)
            status_list.extend(QrStatusView.refresh_status([qr_account, ]))
        except QrAccount.DoesNotExist:
            pass
        sorted_status_list = sorted(status_list, key=lambda status: status['time_stamp'], reverse=True)
        if lt_st_time:
            raw_struct_time = time.strptime(lt_st_time, '%Y-%m-%d %H:%M:%S')
            lt_st_time_epoch = time.mktime(raw_struct_time)
            sorted_status_list = filter(time_filter_wrapper(lt_st_time_epoch), sorted_status_list)
        elif len(sorted_status_list) > 10:
            sorted_status_list = sorted_status_list[:10]

        # sorted_status_list = sorted(status_list, key=lambda tw_status: tw_status['id'], cmp=status_cmp)
        return JsonResponse({'status_list': sorted_status_list})
    raise Http404


@login_required
def more_status_by_site(request):
    pass


@login_required
def more_status_by_flr(request):
    pass


def time_filter_wrapper(lt_st_time_epoch):
    def time_filter(status):
        raw_struct_time = time.strptime(status['time_stamp'], '%Y-%m-%d %H:%M:%S')
        time_epoch = time.mktime(raw_struct_time)
        return time_epoch > lt_st_time_epoch
    return time_filter

templates/ChasingSomeoneApp/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit</title>
    <link rel="stylesheet" type = "text/css" href="../../static/css/edit.css">
    <link rel="stylesheet" type = "text/css" href="../../static/css/header.css">
</head>
<body>

    <div class="header" onscroll = "no">
        <div class="header-left">
            <div class = "nav">
                Home
            </div>
            <div class = "nav">
                Following
            </div>
            <div class = "nav">
                Favorite
            </div>
            <div class = "nav">
                Information
            </div>
        </div>
        <div class = "header-right">
            <a class = "logout" href="{% url 'ChasingSomeoneApp:user_logout' %}" >Logout</a>
        </div>
    </div>

    <div class="title">
        <div class="title-1">ChasingSomeone</div>
        <div class="title-2">Edit</div>
    </div>

     <div class="content">

        <div class="description">
            Personal Information
        </div>

        <div class="content-item">
            <div class="item-left">Name:</div>
            <input type="text" value="charles" class="name-input">
        </div>

        <div class="content-item">
            <div class="item-left">Profile Picture:</div>
            <div class="item-right">
                <img src = "../../static/img/profile_picture.png" alt="large profile picture">
            </div>
        </div>

        <div class="description">
            Website Information
        </div>
        <div class="website-content">
            <div class="sub-description">
                <div class="website-name">Twitter</div>
                <button class="delete-button" value="delete">delete</button>
                <button class="delete-button" value="add">add</button>
            </div>
            <div class="content-item-website">
                <div class="website-item-left">tweets:</div>
                <input class="twitter-tweets" type="text">
            </div>
        </div>

         <div class="website-content">
            <div class="sub-description">
                <div class="website-name">Quora</div>
                <button class="delete-button" value="delete">delete</button>
                <button class="delete-button" value="add">add</button>
            </div>
            <div class="content-item-website">
                <div class="website-item-left">quora ID:</div>
                <input class="twitter-tweets" type="text">
            </div>
        </div>

         <button class="save-change">save</button>
    </div>

</body>
</html>

templates/ChasingSomeoneApp/following.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Following List</title>
    <link href="{% static 'css/following.css' %}" type="text/css" rel="stylesheet"/>
    <link href="{% static 'css/header.css' %}" type="text/css" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'js/jquery-2.0.0.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/Cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/following.js' %}"></script>
</head>
<body>
    {% include "ChasingSomeoneApp/header.html" %}

    <div class="content">
        <div id="follower_list" class="follower-list">
            <div class="title">Following List</div>
            <div class="function-button">
                <button id="btn_goto_add_follower" >add</button>
                <button>edit</button>
            </div>
            <!--following list-->
            <div id="following_list" class="following-list">
            {% for flr in flr_list %}
                <div class="following-item" id="{{ flr.flr_id }}">
                    <div class="profile-picture">
                        <img src="../../static/img/profile_picture.png">
                    </div>
                    <div class="following-name">
                        {{ flr.flr_name }}
                    </div>
                    <a href="#">more information</a>
                </div>
                {% endfor %}
            </div>
        </div>

        <div id="add_section" class="add-section" style="display: none">
        <!--add follower name-->
            <div id="follower_profile" class="follower-name">
            <div class="add-hint">Add the people you want to follow's nickname:</div>
            <input type="text" name="fname" />
            <button id="btn_add_follower" >next</button>
            <button id="btn_cancel_add_follower" >cancel</button>
        </div>

        <!--add social website-->
            <div id="add_account_div" class="content-right-add" style="display: none">
            <div class = "hint">
                Choose the social network and add your following!
            </div>

            <div id="demo" class = "socialnetwork collapse">
                <div class = "title">
                    <div class = "logo">
                    Twitter
                    </div>
                </div>

                <div class = "add-form" style="display: none">
{#                    <form method="post" action = "#" enctype="multipart/form-data">#}
                        <div class = "form-left">
                            <p for="#" >Username:</p>
{#                            <p for="#">User ID:</p>#}
                        </div>

                        <div class = "form-right">
                            <input id="screen_name" maxlength="30" name="username" type="text">
{#                            <input id="follower_id" maxlength="30" name="userid" type="text">#}
                        </div>

                        <input name="submit" value="check" type="button" class="confirm-button" data-act_type="twitter">
{#                    </form>#}
                </div>
            </div>

            <div class = "socialnetwork">
                <div class = "title">
                    <div class = "logo">
                    Quora
                    </div>
                </div>

                <div class = "add-form" style="display: none">
{#                    <form method="post" action = "#" enctype="multipart/form-data">#}
                        <div class = "form-left">
                            <p for="#" >Username:</p>
{#                            <p for="#">User ID:</p>#}
                        </div>

                        <div class = "form-right">
                            <input id="user_name" maxlength="30" name="username" type="text">
{#                            <input id="id_email" maxlength="254" name="email" type="email">#}
                        </div>

                        <input name="submit" value="check" type="submit" class="confirm-button" data-act_type="quora">
{#                    </form>#}
                </div>
            </div>

            <!--summary submit-->
            <label class="end-hint">Check again. If there is no fault, press the "OK" button to add the following</label>
            <input id="btn_save_accounts" type="submit" value="OK" class="end-submit">
        </div>

        </div>
    </div>

</body>
</html>

templates/ChasingSomeoneApp/header.html
 <div class="header" onscroll = "no">
        <div class="header-left">
            <div class = "nav">
                <a name="home_button" href="{% url 'ChasingSomeoneApp:user_home' %}">Home</a>
            </div>
            <div class = "nav">
                <a name="following_button" href="{% url 'ChasingSomeoneApp:browse_following' %}">Following</a>
            </div>
{#            <div class = "nav">#}
{#                <a name="favorite_button" href="{% url 'ChasingSomeoneApp:user_home' %}">Favorite</a>#}
{#            </div>#}
{#            <div class = "nav">#}
{#                <a name="information_button" href="{% url 'ChasingSomeoneApp:user_home' %}">Information</a>#}
{#            </div>#}
        </div>
        <div class = "header-right">
            <a class = "logout" href="{% url 'ChasingSomeoneApp:user_logout' %}" >Logout</a>
        </div>
    </div>

{# <script>#}
{#$(function(){#}
{#    var $header=$(".header");#}
{#    var offset=$header.offset();#}
{#    $(window).scroll(function(){#}
{#        var scrollTop=$(window).scrollTop();#}
{#        if(offset.top!=scrollTop){#}
{#            $header.addClass("fixed");#}
{#        }else{#}
{#            $header.removeClass("fixed");#}
{#        }#}
{#    });})#}
{##}
{# </script>#}

templates/ChasingSomeoneApp/information.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Information</title>
    <link rel="stylesheet" type="text/css" href="../../static/css/information.css" />
</head>
<body>

    <div class="header" onscroll = "no">
        <div class="header-left">
            <div class = "nav">
                Home
            </div>
            <div class = "nav">
                Following
            </div>
            <div class = "nav">
                Favorite
            </div>
            <div class = "nav">
                Information
            </div>
        </div>
        <div class = "header-right">
            <a class = "logout" href="{% url 'ChasingSomeoneApp:user_logout' %}" >Logout</a>
        </div>
    </div>

    <div class="title">
        <div class="title-1">ChasingSomeone</div>
        <div class="title-2">Overview</div>
    </div>
    <div class="content">
        <div class="content-item">
            <div class="item-left">Name:</div>
            <div class="item-right">charles</div>
        </div>

        <div class="content-item">
            <div class="item-left">Profile Picture:</div>
            <div class="item-right">
                <div class="profile-photo-small">
                    <img src = "../../static/img/" alt="small profile picture">
                </div>
                <div class="profile-photo-large">
                    <img src = "../../static/img/" alt="large profile picture">
                </div>
            </div>
        </div>

        <div class="content-item">
            <div class="item-left">Birthday:</div>
            <div class="item-right">Jan 01 1993</div>
        </div>

        <div class="content-item">
            <div class="item-left">Email:</div>
            <div class="item-right">Charleszhuochen@gmail.com</div>
        </div>

    </div>

</body>
</html>

templates/ChasingSomeoneApp/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Login-Chasing</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link href = "{% static 'css/base.css' %}" type="text/css" rel="stylesheet">
    <link href = "{% static 'css/login.css' %}" type="text/css" rel="stylesheet">
</head>

<body>
    <div class = "login-form">
        <div class="logo">ChasingSomeone</div>
        <p>Sign In Here!</p>
        <div class = "content">
            <form id="login_form" method="post" action="/ChasingSomeone/login/">
           {% csrf_token %}
            {% if error %}
                <p style="color: #ec407a;margin-left: 43%">Error:{{ errorMessage }}</p><br/>
            {% endif %}
            <div class = "content-left">
                <p  for="id_username" >Email:</p>
                <p  for="id_password" style="margin-right:37px">Password:</p>
            </div>
                
            <div class = "content-right">
                <input type="text" name="username" value="" />
                <input type="password" name="password" value="" />
            </div>

            <input type="submit" value="submit" class = "login-button" name = "login"/>

            </form>
            <div class = "content-bottom">
                <label>Doesn't have an account?</label>
                <a name="signup" href="{% url 'ChasingSomeoneApp:register' %}">Register Here</a>
            </div>
            
        </div>
    </div>



</body>
</html>

templates/ChasingSomeoneApp/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Register-Chasing</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<link href = "{% static 'css/base.css' %}" type="text/css" rel="stylesheet">
	<link href = "{% static 'css/register.css' %}" type="text/css" rel="stylesheet">

</head>

<body>
	<div class = "nav">
        <a href="{% url 'ChasingSomeoneApp:user_login' %}" name="back_signIn_button" class = "button-signin">Sign In</a>
	</div>
    {% if registered %}
    <div class = "welcome">Thanks for registering!</div>
    <br/>
    <a href="{% url 'ChasingSomeoneApp:user_login' %}" name="back_button" class = "button-back">Back to Home Page</a>
    {% else %}
    <div class="logo">ChasingSomeone</div>
	<div class = "welcome">
		Create Your Chasing Someone Account!
	</div>

	<div class="register-form">
		<div class = "content">
			<form id="user_form" method="post" action = "{% url 'ChasingSomeoneApp:register' %}" enctype="multipart/form-data">
			{% csrf_token %}

			<div class = "content-left">
{#				<p for="id_username" >Username:</p>#}
				<p for="id_email">Email address:</p>
				<p for="id_password" style="margin-right:37px">Password:</p>
                <p for="id_password" style="margin-right:37px">Password again:</p>
			</div>

			<div class = "content-right">
{#				<input id="id_username" maxlength="30" name="username" type="text" title = "Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.">#}
				<input id="id_email" maxlength="254" name="email" type="email">
				<input id="id_password" name="password1" type="password">
                <input id="id_password" name="password2" type="password">
			</div>
		
            <input name="submit" value="Register" type="submit" class="register-button">
            </form>
        </div>
	</div>
    {% endif %}
</body>
</html>